import StyleDictionary from 'style-dictionary';
import { readFileSync } from 'fs';

// ─── helpers ────────────────────────────────────────────────────────────────

/** Flatten nested token object → { 'color-brand-orange': { value, comment } } */
function flattenTokens(obj, prefix = '') {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}-${key}` : key;
    if (val && typeof val === 'object' && 'value' in val) {
      result[path] = val;
    } else if (val && typeof val === 'object') {
      Object.assign(result, flattenTokens(val, path));
    }
  }
  return result;
}

const raw = JSON.parse(readFileSync('./src/tokens.json', 'utf-8'));
const flat = flattenTokens(raw);

// ─── CSS output ─────────────────────────────────────────────────────────────

function buildCSS(tokens) {
  const sections = {
    'Brand Colors':    (k) => k.startsWith('color-brand-'),
    'Backgrounds':     (k) => k.startsWith('color-bg-'),
    'Borders':         (k) => k.startsWith('color-border-'),
    'Text':            (k) => k.startsWith('color-text-'),
    'Semantic':        (k) => k.startsWith('color-semantic-'),
    'Neutral':         (k) => k.startsWith('color-neutral-'),
    'Typography':      (k) => k.startsWith('typography-font-') || k.startsWith('typography-size-') || k.startsWith('typography-weight-') || k.startsWith('typography-line') || k.startsWith('typography-letter'),
    'Radius':          (k) => k.startsWith('radius-'),
    'Spacing':         (k) => k.startsWith('spacing-'),
    'Shadow':          (k) => k.startsWith('shadow-'),
    'Motion':          (k) => k.startsWith('motion-'),
    'Z-Index':         (k) => k.startsWith('z-index-'),
    'Breakpoints':     (k) => k.startsWith('breakpoint-'),
    'Layout':          (k) => k.startsWith('layout-'),
  };

  const divider = (label) =>
    `\n  /* ${'─'.repeat(41)}\n     ${label}\n  ${'─'.repeat(41)} */`;

  let vars = '';
  for (const [label, match] of Object.entries(sections)) {
    const entries = Object.entries(tokens).filter(([k]) => match(k));
    if (!entries.length) continue;
    vars += divider(label) + '\n';
    for (const [key, { value, comment }] of entries) {
      const cssVar = `--${key}`;
      const padding = Math.max(1, 34 - cssVar.length);
      const note = comment ? `   /* ${comment} */` : '';
      vars += `  ${cssVar}:${' '.repeat(padding)}${value};${note}\n`;
    }
  }

  // Shadcn aliases
  vars += divider('Shadcn-compatible aliases') + '\n';
  const shadcn = {
    '--background':           'var(--color-bg-base)',
    '--foreground':           'var(--color-text-primary)',
    '--card':                 'var(--color-bg-surface)',
    '--card-foreground':      'var(--color-text-primary)',
    '--popover':              'var(--color-bg-elevated)',
    '--popover-foreground':   'var(--color-text-primary)',
    '--primary':              'var(--color-brand-orange)',
    '--primary-foreground':   '#ffffff',
    '--secondary':            'var(--color-bg-hover)',
    '--secondary-foreground': 'var(--color-text-primary)',
    '--muted':                'var(--color-bg-elevated)',
    '--muted-foreground':     'var(--color-text-secondary)',
    '--accent':               'var(--color-brand-teal)',
    '--accent-foreground':    '#ffffff',
    '--destructive':          'var(--color-semantic-danger)',
    '--destructive-fg':       'var(--color-semantic-danger-fg)',
    '--border-color':         'var(--color-border-default)',
    '--input-border':         'var(--color-border-strong)',
    '--ring':                 'var(--color-brand-orange-border)',
    '--radius':               'var(--radius-card)',
  };
  for (const [k, v] of Object.entries(shadcn)) {
    const padding = Math.max(1, 34 - k.length);
    vars += `  ${k}:${' '.repeat(padding)}${v};\n`;
  }

  return `/**
 * AgentisPay — Design Tokens
 * Auto-generated by Style Dictionary. DO NOT edit directly.
 * Source: packages/tokens/src/tokens.json
 *
 * Usage:
 *   @import '@bipa/tokens';
 */

:root {\n${vars}}\n`;
}

// ─── SCSS output ────────────────────────────────────────────────────────────

function buildSCSS(tokens) {
  let out = `// AgentisPay — Design Tokens (SCSS)\n// Auto-generated. DO NOT edit directly.\n\n`;
  for (const [key, { value, comment }] of Object.entries(tokens)) {
    const note = comment ? ` // ${comment}` : '';
    out += `$${key}: ${value};${note}\n`;
  }
  return out;
}

// ─── JS/ESM output ──────────────────────────────────────────────────────────

function buildJS(tokens) {
  let out = `// AgentisPay — Design Tokens (ESM)\n// Auto-generated. DO NOT edit directly.\n\n`;
  // Named exports
  for (const [key, { value }] of Object.entries(tokens)) {
    const name = key.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
    const safeVal = typeof value === 'string' ? `'${value}'` : value;
    out += `export const ${name} = ${safeVal};\n`;
  }
  // Default export as grouped object
  out += `\nexport const tokens = {\n`;
  for (const [key, { value }] of Object.entries(tokens)) {
    const safeVal = typeof value === 'string' ? `'${value}'` : value;
    out += `  '${key}': ${safeVal},\n`;
  }
  out += `};\n\nexport default tokens;\n`;
  return out;
}

// ─── Flat JSON output ────────────────────────────────────────────────────────

function buildJSON(tokens) {
  const out = {};
  for (const [key, { value, comment }] of Object.entries(tokens)) {
    out[key] = { value, ...(comment ? { comment } : {}) };
  }
  return JSON.stringify(out, null, 2) + '\n';
}

// ─── Light theme CSS output ──────────────────────────────────────────────────

function buildLightThemeCSS(lightTokens) {
  const flat = flattenTokens(lightTokens);
  let vars = '';
  for (const [key, { value, comment }] of Object.entries(flat)) {
    const cssVar = `--${key}`;
    const padding = Math.max(1, 34 - cssVar.length);
    const note = comment ? `   /* ${comment} */` : '';
    vars += `  ${cssVar}:${' '.repeat(padding)}${value};${note}\n`;
  }
  // Shadcn aliases for light mode
  const shadcn = {
    '--background':           'var(--color-bg-base)',
    '--foreground':           'var(--color-text-primary)',
    '--card':                 'var(--color-bg-surface)',
    '--card-foreground':      'var(--color-text-primary)',
    '--popover':              'var(--color-bg-elevated)',
    '--popover-foreground':   'var(--color-text-primary)',
    '--muted':                'var(--color-bg-elevated)',
    '--muted-foreground':     'var(--color-text-secondary)',
    '--border-color':         'var(--color-border-default)',
    '--input-border':         'var(--color-border-strong)',
  };
  for (const [k, v] of Object.entries(shadcn)) {
    const padding = Math.max(1, 34 - k.length);
    vars += `  ${k}:${' '.repeat(padding)}${v};\n`;
  }
  return `\n[data-theme="light"] {\n${vars}}\n`;
}

// ─── Write files ────────────────────────────────────────────────────────────

import { writeFileSync, mkdirSync } from 'fs';

mkdirSync('./dist', { recursive: true });

// Build dark (base) + light theme CSS
const lightTokens = raw.themes?.light ?? {};
const lightCSS = Object.keys(lightTokens).length ? buildLightThemeCSS(lightTokens) : '';
writeFileSync('./dist/tokens.css',  buildCSS(flat) + lightCSS);
writeFileSync('./dist/tokens.scss', buildSCSS(flat));
writeFileSync('./dist/tokens.js',   buildJS(flat));
writeFileSync('./dist/tokens.json', buildJSON(flat));

console.log('✓ tokens.css  (dark :root + [data-theme="light"])');
console.log('✓ tokens.scss');
console.log('✓ tokens.js');
console.log('✓ tokens.json');
console.log('\n@bipa/tokens build complete → dist/');
